# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.21.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pugalol/Desktop/matx/MaterialX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pugalol/Desktop/matx/MaterialX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pugalol/Desktop/matx/MaterialX/CMakeFiles /Users/pugalol/Desktop/matx/MaterialX//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pugalol/Desktop/matx/MaterialX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MaterialXCore

# Build rule for target.
MaterialXCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXCore
.PHONY : MaterialXCore

# fast build rule for target.
MaterialXCore/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXCore/CMakeFiles/MaterialXCore.dir/build.make source/MaterialXCore/CMakeFiles/MaterialXCore.dir/build
.PHONY : MaterialXCore/fast

#=============================================================================
# Target rules for targets named MaterialXFormat

# Build rule for target.
MaterialXFormat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXFormat
.PHONY : MaterialXFormat

# fast build rule for target.
MaterialXFormat/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXFormat/CMakeFiles/MaterialXFormat.dir/build.make source/MaterialXFormat/CMakeFiles/MaterialXFormat.dir/build
.PHONY : MaterialXFormat/fast

#=============================================================================
# Target rules for targets named MaterialXGenShader

# Build rule for target.
MaterialXGenShader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenShader
.PHONY : MaterialXGenShader

# fast build rule for target.
MaterialXGenShader/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenShader/CMakeFiles/MaterialXGenShader.dir/build.make source/MaterialXGenShader/CMakeFiles/MaterialXGenShader.dir/build
.PHONY : MaterialXGenShader/fast

#=============================================================================
# Target rules for targets named MaterialXGenGlsl

# Build rule for target.
MaterialXGenGlsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenGlsl
.PHONY : MaterialXGenGlsl

# fast build rule for target.
MaterialXGenGlsl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenGlsl/CMakeFiles/MaterialXGenGlsl.dir/build.make source/MaterialXGenGlsl/CMakeFiles/MaterialXGenGlsl.dir/build
.PHONY : MaterialXGenGlsl/fast

#=============================================================================
# Target rules for targets named MaterialXGenOsl

# Build rule for target.
MaterialXGenOsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenOsl
.PHONY : MaterialXGenOsl

# fast build rule for target.
MaterialXGenOsl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenOsl/CMakeFiles/MaterialXGenOsl.dir/build.make source/MaterialXGenOsl/CMakeFiles/MaterialXGenOsl.dir/build
.PHONY : MaterialXGenOsl/fast

#=============================================================================
# Target rules for targets named MaterialXGenMdl

# Build rule for target.
MaterialXGenMdl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenMdl
.PHONY : MaterialXGenMdl

# fast build rule for target.
MaterialXGenMdl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenMdl/CMakeFiles/MaterialXGenMdl.dir/build.make source/MaterialXGenMdl/CMakeFiles/MaterialXGenMdl.dir/build
.PHONY : MaterialXGenMdl/fast

#=============================================================================
# Target rules for targets named MaterialXGenOgsXml

# Build rule for target.
MaterialXGenOgsXml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenOgsXml
.PHONY : MaterialXGenOgsXml

# fast build rule for target.
MaterialXGenOgsXml/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenOgsXml/CMakeFiles/MaterialXGenOgsXml.dir/build.make source/MaterialXGenOgsXml/CMakeFiles/MaterialXGenOgsXml.dir/build
.PHONY : MaterialXGenOgsXml/fast

#=============================================================================
# Target rules for targets named MaterialXGenOgsFx

# Build rule for target.
MaterialXGenOgsFx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenOgsFx
.PHONY : MaterialXGenOgsFx

# fast build rule for target.
MaterialXGenOgsFx/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenOgsFx/CMakeFiles/MaterialXGenOgsFx.dir/build.make source/MaterialXGenOgsFx/CMakeFiles/MaterialXGenOgsFx.dir/build
.PHONY : MaterialXGenOgsFx/fast

#=============================================================================
# Target rules for targets named MaterialXGenEssl

# Build rule for target.
MaterialXGenEssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenEssl
.PHONY : MaterialXGenEssl

# fast build rule for target.
MaterialXGenEssl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenEssl/CMakeFiles/MaterialXGenEssl.dir/build.make source/MaterialXGenEssl/CMakeFiles/MaterialXGenEssl.dir/build
.PHONY : MaterialXGenEssl/fast

#=============================================================================
# Target rules for targets named MaterialXGenArnold

# Build rule for target.
MaterialXGenArnold: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXGenArnold
.PHONY : MaterialXGenArnold

# fast build rule for target.
MaterialXGenArnold/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXGenArnold/CMakeFiles/MaterialXGenArnold.dir/build.make source/MaterialXGenArnold/CMakeFiles/MaterialXGenArnold.dir/build
.PHONY : MaterialXGenArnold/fast

#=============================================================================
# Target rules for targets named MaterialXRender

# Build rule for target.
MaterialXRender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXRender
.PHONY : MaterialXRender

# fast build rule for target.
MaterialXRender/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXRender/CMakeFiles/MaterialXRender.dir/build.make source/MaterialXRender/CMakeFiles/MaterialXRender.dir/build
.PHONY : MaterialXRender/fast

#=============================================================================
# Target rules for targets named MaterialXRenderOsl

# Build rule for target.
MaterialXRenderOsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXRenderOsl
.PHONY : MaterialXRenderOsl

# fast build rule for target.
MaterialXRenderOsl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXRenderOsl/CMakeFiles/MaterialXRenderOsl.dir/build.make source/MaterialXRenderOsl/CMakeFiles/MaterialXRenderOsl.dir/build
.PHONY : MaterialXRenderOsl/fast

#=============================================================================
# Target rules for targets named MaterialXRenderHw

# Build rule for target.
MaterialXRenderHw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXRenderHw
.PHONY : MaterialXRenderHw

# fast build rule for target.
MaterialXRenderHw/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXRenderHw/CMakeFiles/MaterialXRenderHw.dir/build.make source/MaterialXRenderHw/CMakeFiles/MaterialXRenderHw.dir/build
.PHONY : MaterialXRenderHw/fast

#=============================================================================
# Target rules for targets named MaterialXRenderGlsl

# Build rule for target.
MaterialXRenderGlsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXRenderGlsl
.PHONY : MaterialXRenderGlsl

# fast build rule for target.
MaterialXRenderGlsl/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXRenderGlsl/CMakeFiles/MaterialXRenderGlsl.dir/build.make source/MaterialXRenderGlsl/CMakeFiles/MaterialXRenderGlsl.dir/build
.PHONY : MaterialXRenderGlsl/fast

#=============================================================================
# Target rules for targets named MaterialXContrib

# Build rule for target.
MaterialXContrib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXContrib
.PHONY : MaterialXContrib

# fast build rule for target.
MaterialXContrib/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXContrib/CMakeFiles/MaterialXContrib.dir/build.make source/MaterialXContrib/CMakeFiles/MaterialXContrib.dir/build
.PHONY : MaterialXContrib/fast

#=============================================================================
# Target rules for targets named MaterialXView

# Build rule for target.
MaterialXView: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXView
.PHONY : MaterialXView

# fast build rule for target.
MaterialXView/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXView/CMakeFiles/MaterialXView.dir/build.make source/MaterialXView/CMakeFiles/MaterialXView.dir/build
.PHONY : MaterialXView/fast

#=============================================================================
# Target rules for targets named nanogui

# Build rule for target.
nanogui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanogui
.PHONY : nanogui

# fast build rule for target.
nanogui/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXView/external/NanoGUI/CMakeFiles/nanogui.dir/build.make source/MaterialXView/external/NanoGUI/CMakeFiles/nanogui.dir/build
.PHONY : nanogui/fast

#=============================================================================
# Target rules for targets named nanogui-obj

# Build rule for target.
nanogui-obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanogui-obj
.PHONY : nanogui-obj

# fast build rule for target.
nanogui-obj/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXView/external/NanoGUI/CMakeFiles/nanogui-obj.dir/build.make source/MaterialXView/external/NanoGUI/CMakeFiles/nanogui-obj.dir/build
.PHONY : nanogui-obj/fast

#=============================================================================
# Target rules for targets named glfw_objects

# Build rule for target.
glfw_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw_objects
.PHONY : glfw_objects

# fast build rule for target.
glfw_objects/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXView/external/NanoGUI/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build.make source/MaterialXView/external/NanoGUI/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build
.PHONY : glfw_objects/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXView/external/NanoGUI/ext_build/glfw/src/CMakeFiles/glfw.dir/build.make source/MaterialXView/external/NanoGUI/ext_build/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named MaterialXTest

# Build rule for target.
MaterialXTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialXTest
.PHONY : MaterialXTest

# fast build rule for target.
MaterialXTest/fast:
	$(MAKE) $(MAKESILENT) -f source/MaterialXTest/CMakeFiles/MaterialXTest.dir/build.make source/MaterialXTest/CMakeFiles/MaterialXTest.dir/build
.PHONY : MaterialXTest/fast

#=============================================================================
# Target rules for targets named JsMaterialXGenShader

# Build rule for target.
JsMaterialXGenShader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JsMaterialXGenShader
.PHONY : JsMaterialXGenShader

# fast build rule for target.
JsMaterialXGenShader/fast:
	$(MAKE) $(MAKESILENT) -f source/JsMaterialX/CMakeFiles/JsMaterialXGenShader.dir/build.make source/JsMaterialX/CMakeFiles/JsMaterialXGenShader.dir/build
.PHONY : JsMaterialXGenShader/fast

#=============================================================================
# Target rules for targets named JsMaterialXCore

# Build rule for target.
JsMaterialXCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JsMaterialXCore
.PHONY : JsMaterialXCore

# fast build rule for target.
JsMaterialXCore/fast:
	$(MAKE) $(MAKESILENT) -f source/JsMaterialX/CMakeFiles/JsMaterialXCore.dir/build.make source/JsMaterialX/CMakeFiles/JsMaterialXCore.dir/build
.PHONY : JsMaterialXCore/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... JsMaterialXCore"
	@echo "... JsMaterialXGenShader"
	@echo "... MaterialXContrib"
	@echo "... MaterialXCore"
	@echo "... MaterialXFormat"
	@echo "... MaterialXGenArnold"
	@echo "... MaterialXGenEssl"
	@echo "... MaterialXGenGlsl"
	@echo "... MaterialXGenMdl"
	@echo "... MaterialXGenOgsFx"
	@echo "... MaterialXGenOgsXml"
	@echo "... MaterialXGenOsl"
	@echo "... MaterialXGenShader"
	@echo "... MaterialXRender"
	@echo "... MaterialXRenderGlsl"
	@echo "... MaterialXRenderHw"
	@echo "... MaterialXRenderOsl"
	@echo "... MaterialXTest"
	@echo "... MaterialXView"
	@echo "... glfw"
	@echo "... glfw_objects"
	@echo "... nanogui"
	@echo "... nanogui-obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

