# CMake generated Testfile for 
# Source directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat
# Build directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MaterialXTest_Syntactic_operations "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "Syntactic operations")
set_tests_properties(MaterialXTest_Syntactic_operations PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_File_system_operations "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "File system operations")
set_tests_properties(MaterialXTest_File_system_operations PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_File_search_path_operations "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "File search path operations")
set_tests_properties(MaterialXTest_File_search_path_operations PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_Flatten_filenames "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "Flatten filenames")
set_tests_properties(MaterialXTest_Flatten_filenames PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_Export_Document "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "Export Document")
set_tests_properties(MaterialXTest_Export_Document PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_File_Path_Predicate "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "File Path Predicate")
set_tests_properties(MaterialXTest_File_Path_Predicate PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_Load_content "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "Load content")
set_tests_properties(MaterialXTest_Load_content PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_In_memory_xincludes "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "In memory xincludes")
set_tests_properties(MaterialXTest_In_memory_xincludes PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
add_test(MaterialXTest_Load_locale_content "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "Load locale content")
set_tests_properties(MaterialXTest_Load_locale_content PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXFormat/CMakeLists.txt;0;")
