# CMake generated Testfile for 
# Source directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl
# Build directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MaterialXTest_GenShader_OSL_Syntax "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: OSL Syntax")
set_tests_properties(MaterialXTest_GenShader_OSL_Syntax PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_OSL_Implementation_Check "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: OSL Implementation Check")
set_tests_properties(MaterialXTest_GenShader_OSL_Implementation_Check PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_OSL_Unique_Names "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: OSL Unique Names")
set_tests_properties(MaterialXTest_GenShader_OSL_Unique_Names PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_OSL_Metadata "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: OSL Metadata")
set_tests_properties(MaterialXTest_GenShader_OSL_Metadata PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_OSL_Shader_Generation "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: OSL Shader Generation")
set_tests_properties(MaterialXTest_GenShader_OSL_Shader_Generation PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenOsl/CMakeLists.txt;0;")
