# CMake generated Testfile for 
# Source directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl
# Build directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MaterialXTest_GenShader_GLSL_Syntax_Check "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: GLSL Syntax Check")
set_tests_properties(MaterialXTest_GenShader_GLSL_Syntax_Check PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_GLSL_Implementation_Check "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: GLSL Implementation Check")
set_tests_properties(MaterialXTest_GenShader_GLSL_Implementation_Check PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_GLSL_Unique_Names "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: GLSL Unique Names")
set_tests_properties(MaterialXTest_GenShader_GLSL_Unique_Names PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_Bind_Light_Shaders "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Bind Light Shaders")
set_tests_properties(MaterialXTest_GenShader_Bind_Light_Shaders PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_GLSL_Shader_Generation "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: GLSL Shader Generation")
set_tests_properties(MaterialXTest_GenShader_GLSL_Shader_Generation PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_GLSL_Shader_with_Layout_Generation "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: GLSL Shader with Layout Generation")
set_tests_properties(MaterialXTest_GenShader_GLSL_Shader_with_Layout_Generation PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenGlsl/CMakeLists.txt;0;")
