//
// TM & (c) 2020 Lucasfilm Entertainment Company Ltd. and Lucasfilm Ltd.
// All rights reserved. See LICENSE.txt for license.
//

#ifndef MATERIALX_CODEGEN_SOURCECODE_H
#define MATERIALX_CODEGEN_SOURCECODE_H

/// @file SourceCode.h
/// TODO: Docs

#include <MaterialXCodegen/Library.h>
#include <MaterialXRuntime/RtToken.h>

#include <MaterialXCodegen/Syntax.h>

namespace MaterialX
{
namespace Codegen
{

/// @class SourceCode
/// Container for source code generated by fragment compilers.
class SourceCode
{
public:
    /// Contructor.
    SourceCode();

    /// Start a new scope using the given bracket type.
    void beginScope(Syntax::Punctuation punc = Syntax::CURLY_BRACKETS);

    /// End the current scope.
    void endScope(bool semicolon = false, bool newline = true);

    /// Start a new line.
    void beginLine();

    /// End the current line.
    void endLine(bool semicolon = true);

    /// Add a newline character.
    void newLine();

    /// Add a generic code string.
    void addString(const string& str);

    /// Add a line of code, optionally appending a semicolon.
    void addLine(const string& str, bool semicolon = true);

    /// Set the given function as defined in this source code.
    void setDefined(const RtToken& function);

    /// Return true if the given function has been defined in this source code.
    bool isDefined(const RtToken& function) const;

    /// Set the given file as included in this source code.
    void setIncluded(const RtToken& file);

    /// Return true if the given file is set as included in this source code.
    bool isIncluded(const RtToken& file) const;

    /// Return the source code.
    const string& asString() const;

    /// Return the source code.
    string& asString();

private:
    int _indentations;
    vector<Syntax::Punctuation> _scopes;
    RtTokenSet _functions;
    RtTokenSet _includes;
    string _code;
};

} // namespace Codegen
} // namespace MaterialX

#endif
