# CMake generated Testfile for 
# Source directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader
# Build directory: /Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MaterialXTest_GenShader_Utilities "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Utilities")
set_tests_properties(MaterialXTest_GenShader_Utilities PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_Valid_Libraries "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Valid Libraries")
set_tests_properties(MaterialXTest_GenShader_Valid_Libraries PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_TypeDesc_Check "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: TypeDesc Check")
set_tests_properties(MaterialXTest_GenShader_TypeDesc_Check PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_Graph_Nodedf_Transparency_Check "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Graph + Nodedf Transparency Check")
set_tests_properties(MaterialXTest_GenShader_Graph_Nodedf_Transparency_Check PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_Shader_Translation "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Shader Translation")
set_tests_properties(MaterialXTest_GenShader_Shader_Translation PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
add_test(MaterialXTest_GenShader_Transparency_ "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXTest" "GenShader: Transparency ")
set_tests_properties(MaterialXTest_GenShader_Transparency_ PROPERTIES  WORKING_DIRECTORY "/Users/pugalol/Desktop/matx/MaterialX/bin" _BACKTRACE_TRIPLES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/CMakeLists.txt;18;add_test;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;6;add_tests;/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXTest/MaterialXGenShader/CMakeLists.txt;0;")
