# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget MaterialXCore MaterialXFormat MaterialXGenShader MaterialXGenGlsl MaterialXGenOsl MaterialXGenMdl MaterialXGenOgsXml MaterialXGenOgsFx MaterialXGenEssl MaterialXGenArnold MaterialXRender MaterialXRenderOsl MaterialXRenderHw MaterialXRenderGlsl MaterialXContrib MaterialXView)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target MaterialXCore
add_library(MaterialXCore STATIC IMPORTED)

set_target_properties(MaterialXCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXCore/../"
)

# Create imported target MaterialXFormat
add_library(MaterialXFormat STATIC IMPORTED)

set_target_properties(MaterialXFormat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXFormat/../"
  INTERFACE_LINK_LIBRARIES "MaterialXCore"
)

# Create imported target MaterialXGenShader
add_library(MaterialXGenShader STATIC IMPORTED)

set_target_properties(MaterialXGenShader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenShader/../"
  INTERFACE_LINK_LIBRARIES "MaterialXCore;MaterialXFormat"
)

# Create imported target MaterialXGenGlsl
add_library(MaterialXGenGlsl STATIC IMPORTED)

set_target_properties(MaterialXGenGlsl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenGlsl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenShader;MaterialXCore"
)

# Create imported target MaterialXGenOsl
add_library(MaterialXGenOsl STATIC IMPORTED)

set_target_properties(MaterialXGenOsl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenOsl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenShader;MaterialXCore"
)

# Create imported target MaterialXGenMdl
add_library(MaterialXGenMdl STATIC IMPORTED)

set_target_properties(MaterialXGenMdl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenMdl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenShader;MaterialXCore"
)

# Create imported target MaterialXGenOgsXml
add_library(MaterialXGenOgsXml STATIC IMPORTED)

set_target_properties(MaterialXGenOgsXml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenOgsXml/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenGlsl;MaterialXGenShader;MaterialXCore;MaterialXRender;\$<\$<BOOL:OFF>:MaterialXCross>"
)

# Create imported target MaterialXGenOgsFx
add_library(MaterialXGenOgsFx STATIC IMPORTED)

set_target_properties(MaterialXGenOgsFx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenOgsFx/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenGlsl;MaterialXGenShader;MaterialXCore"
)

# Create imported target MaterialXGenEssl
add_library(MaterialXGenEssl STATIC IMPORTED)

set_target_properties(MaterialXGenEssl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenEssl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenGlsl;MaterialXGenShader;MaterialXCore"
)

# Create imported target MaterialXGenArnold
add_library(MaterialXGenArnold STATIC IMPORTED)

set_target_properties(MaterialXGenArnold PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXGenArnold/../"
  INTERFACE_LINK_LIBRARIES "MaterialXGenOsl;MaterialXCore"
)

# Create imported target MaterialXRender
add_library(MaterialXRender STATIC IMPORTED)

set_target_properties(MaterialXRender PROPERTIES
  INTERFACE_LINK_LIBRARIES "MaterialXGenShader"
)

# Create imported target MaterialXRenderOsl
add_library(MaterialXRenderOsl STATIC IMPORTED)

set_target_properties(MaterialXRenderOsl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXRenderOsl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXRender"
)

# Create imported target MaterialXRenderHw
add_library(MaterialXRenderHw STATIC IMPORTED)

set_target_properties(MaterialXRenderHw PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXRenderHw/../"
  INTERFACE_LINK_LIBRARIES "MaterialXRender;-framework Foundation;-framework Cocoa"
)

# Create imported target MaterialXRenderGlsl
add_library(MaterialXRenderGlsl STATIC IMPORTED)

set_target_properties(MaterialXRenderGlsl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXRenderGlsl/../"
  INTERFACE_LINK_LIBRARIES "MaterialXRenderHw;MaterialXGenGlsl;/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework;/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework;-framework Foundation;-framework Cocoa"
)

# Create imported target MaterialXContrib
add_library(MaterialXContrib STATIC IMPORTED)

set_target_properties(MaterialXContrib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/pugalol/Desktop/matx/MaterialX/source/MaterialXContrib/../"
  INTERFACE_LINK_LIBRARIES "MaterialXRender"
)

# Create imported target MaterialXView
add_executable(MaterialXView IMPORTED)

# Import target "MaterialXCore" for configuration "Release"
set_property(TARGET MaterialXCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXCore.a"
  )

# Import target "MaterialXFormat" for configuration "Release"
set_property(TARGET MaterialXFormat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXFormat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXFormat.a"
  )

# Import target "MaterialXGenShader" for configuration "Release"
set_property(TARGET MaterialXGenShader APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenShader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenShader.a"
  )

# Import target "MaterialXGenGlsl" for configuration "Release"
set_property(TARGET MaterialXGenGlsl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenGlsl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenGlsl.a"
  )

# Import target "MaterialXGenOsl" for configuration "Release"
set_property(TARGET MaterialXGenOsl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenOsl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenOsl.a"
  )

# Import target "MaterialXGenMdl" for configuration "Release"
set_property(TARGET MaterialXGenMdl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenMdl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenMdl.a"
  )

# Import target "MaterialXGenOgsXml" for configuration "Release"
set_property(TARGET MaterialXGenOgsXml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenOgsXml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenOgsXml.a"
  )

# Import target "MaterialXGenOgsFx" for configuration "Release"
set_property(TARGET MaterialXGenOgsFx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenOgsFx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenOgsFx.a"
  )

# Import target "MaterialXGenEssl" for configuration "Release"
set_property(TARGET MaterialXGenEssl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenEssl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenEssl.a"
  )

# Import target "MaterialXGenArnold" for configuration "Release"
set_property(TARGET MaterialXGenArnold APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXGenArnold PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXGenArnold.a"
  )

# Import target "MaterialXRender" for configuration "Release"
set_property(TARGET MaterialXRender APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXRender PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXRender.a"
  )

# Import target "MaterialXRenderOsl" for configuration "Release"
set_property(TARGET MaterialXRenderOsl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXRenderOsl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXRenderOsl.a"
  )

# Import target "MaterialXRenderHw" for configuration "Release"
set_property(TARGET MaterialXRenderHw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXRenderHw PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXRenderHw.a"
  )

# Import target "MaterialXRenderGlsl" for configuration "Release"
set_property(TARGET MaterialXRenderGlsl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXRenderGlsl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXRenderGlsl.a"
  )

# Import target "MaterialXContrib" for configuration "Release"
set_property(TARGET MaterialXContrib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXContrib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/lib/libMaterialXContrib.a"
  )

# Import target "MaterialXView" for configuration "Release"
set_property(TARGET MaterialXView APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MaterialXView PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/pugalol/Desktop/matx/MaterialX/bin/MaterialXView"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
